var tasks = [
    {
        difficulty: 11,
        id: "",
        year: 2012,
        comp: "JOIsp",
        day: "Day1-1",
        name: "Building 2",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2012/2012-sp-tasks/2012-sp-day1.pdf"
    },
    {
        difficulty: 10,
        id: "",
        year: 2012,
        comp: "JOIsp",
        day: "Day1-2",
        name: "Fish",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2012/2012-sp-tasks/2012-sp-day1.pdf"
    },
    {
        difficulty: 8,
        id: "",
        year: 2012,
        comp: "JOIsp",
        day: "Day1-3",
        name: "JOI Flag",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2012/2012-sp-tasks/2012-sp-day1.pdf"
    },
    {
        difficulty: '',
        id: "JOI12_broadcasting",
        year: 2012,
        comp: "JOIsp",
        day: "Day2-1",
        name: "Broadcasting",
        type: "Output Only",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2012/2012-sp-tasks/2012-sp-day2.pdf"
    },
    {
        difficulty: 11,
        id: "JOI12_constellation",
        year: 2012,
        comp: "JOIsp",
        day: "Day2-2",
        name: "Constellation",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2012/2012-sp-tasks/2012-sp-day2.pdf"
    },
    {
        difficulty: 11,
        id: "JOI12_rotate",
        year: 2012,
        comp: "JOIsp",
        day: "Day2-3",
        name: "Rotate",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2012/2012-sp-tasks/2012-sp-day2.pdf"
    },
    {
        difficulty: 9,
        id: "",
        year: 2012,
        comp: "JOIsp",
        day: "Day3-1",
        name: "Fortune Telling",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2012/2012-sp-tasks/2012-sp-day3.pdf"
    },
    {
        difficulty: 11,
        id: "",
        year: 2012,
        comp: "JOIsp",
        day: "Day3-2",
        name: "Kangaroo",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2012/2012-sp-tasks/2012-sp-day3.pdf"
    },
    {
        difficulty: 12,
        id: "",
        year: 2012,
        comp: "JOIsp",
        day: "Day3-3",
        name: "Sokoban",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2012/2012-sp-tasks/2012-sp-day3.pdf"
    },
    {
        difficulty: 9,
        id: "",
        year: 2012,
        comp: "JOIsp",
        day: "Day4-1",
        name: "Chinese",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2012/2012-sp-tasks/2012-sp-day4.pdf"
    },
    {
        difficulty: 12,
        id: "",
        year: 2012,
        comp: "JOIsp",
        day: "Day4-2",
        name: "Copy and Paste",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2012/2012-sp-tasks/2012-sp-day4.pdf"
    },
    {
        difficulty: 11,
        id: "",
        year: 2012,
        comp: "JOIsp",
        day: "Day4-3",
        name: "Invitation",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2012/2012-sp-tasks/2012-sp-day4.pdf"
    },
    {
        difficulty: 9,
        id: "",
        year: 2013,
        comp: "JOIsp",
        day: "Day1-1",
        name: "Bus Tour",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2013/2013-sp-tasks/2013-sp-day1.pdf"
    },
    {
        difficulty: 9,
        id: "JOI13_collecting",
        year: 2013,
        comp: "JOIsp",
        day: "Day1-2",
        name: "Collecting Images is Fun",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2013/2013-sp-tasks/2013-sp-day1.pdf"
    },
    {
        difficulty: 11,
        id: "",
        year: 2013,
        comp: "JOIsp",
        day: "Day1-3",
        name: "Communication Jamming",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2013/2013-sp-tasks/2013-sp-day1.pdf"
    },
    {
        difficulty: 5,
        id: "",
        year: 2013,
        comp: "JOIsp",
        day: "Day1-4",
        name: "JOI Poster",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2013/2013-sp-tasks/2013-sp-day1.pdf"
    },
    {
        difficulty: 10,
        id: "JOI13_construction",
        year: 2013,
        comp: "JOIsp",
        day: "Day2-1",
        name: "Construction Project",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2013/2013-sp-tasks/2013-sp-day2.pdf"
    },
    {
        difficulty: 8,
        id: "JOI13_mascots",
        year: 2013,
        comp: "JOIsp",
        day: "Day2-2",
        name: "Mascots",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2013/2013-sp-tasks/2013-sp-day2.pdf"
    },
    {
        difficulty: 9,
        id: "JOI13_spy",
        year: 2013,
        comp: "JOIsp",
        day: "Day2-3",
        name: "Spy",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2013/2013-sp-tasks/2013-sp-day2.pdf"
    },
    {
        difficulty: 12,
        id: "JOI13_cake",
        year: 2013,
        comp: "JOIsp",
        day: "Day3-1",
        name: "Cake",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2013/2013-sp-tasks/2013-sp-day3.pdf"
    },
    {
        difficulty: 10,
        id: "JOI13_koala",
        year: 2013,
        comp: "JOIsp",
        day: "Day3-2",
        name: "Koala",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2013/2013-sp-tasks/2013-sp-day3.pdf"
    },
    {
        difficulty: 8,
        id: "JOI13_mountain",
        year: 2013,
        comp: "JOIsp",
        day: "Day3-3",
        name: "Mountain Rescue Team",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2013/2013-sp-tasks/2013-sp-day3.pdf"
    },
    {
        difficulty: 10,
        id: "",
        year: 2013,
        comp: "JOIsp",
        day: "Day4-1",
        name: "Messenger",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2013/2013-sp-tasks/2013-sp-day4.pdf"
    },
    {
        difficulty: 8,
        id: "",
        year: 2013,
        comp: "JOIsp",
        day: "Day4-2",
        name: "Presents",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2013/2013-sp-tasks/2013-sp-day4.pdf"
    },
    {
        difficulty: 12,
        id: "",
        year: 2013,
        comp: "JOIsp",
        day: "Day4-3",
        name: "Spaceships",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2013/2013-sp-tasks/2013-sp-day4.pdf"
    },
    {
        difficulty: 9,
        id: "JOI14_bus",
        year: 2014,
        comp: "JOIsp",
        day: "Day1-1",
        name: "Bus",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2014/2014-sp-tasks/2014-sp-d1.pdf"
    },
    {
        difficulty: 9,
        id: "JOI14_growing",
        year: 2014,
        comp: "JOIsp",
        day: "Day1-2",
        name: "Growing Vegetables is Fun",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2014/2014-sp-tasks/2014-sp-d1.pdf"
    },
    {
        difficulty: 10,
        id: "JOI14_historical",
        year: 2014,
        comp: "JOIsp",
        day: "Day1-3",
        name: "Historical Research",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2014/2014-sp-tasks/2014-sp-d1.pdf"
    },
    {
        difficulty: 7,
        id: "JOI14_ramen",
        year: 2014,
        comp: "JOIsp",
        day: "Day1-4",
        name: "Ramen",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2014/2014-sp-tasks/2014-sp-d1.pdf"
    },
    {
        difficulty: 10,
        id: "JOI14_bottle",
        year: 2014,
        comp: "JOIsp",
        day: "Day2-1",
        name: "Water Bottle",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2014/2014-sp-tasks/2014-sp-d2.pdf"
    },
    {
        difficulty: 9,
        id: "JOI14_friends",
        year: 2014,
        comp: "JOIsp",
        day: "Day2-2",
        name: "Making Friends is Fun",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2014/2014-sp-tasks/2014-sp-d2.pdf"
    },
    {
        difficulty: 10,
        id: "JOI14_stamps",
        year: 2014,
        comp: "JOIsp",
        day: "Day2-3",
        name: "Collecting Stamps",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2014/2014-sp-tasks/2014-sp-d2.pdf"
    },
    {
        difficulty: 6,
        id: "JOI14_joioji",
        year: 2014,
        comp: "JOIsp",
        day: "Day3-1",
        name: "JOIOJI",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2014/2014-sp-tasks/2014-sp-d3.pdf"
    },
    {
        difficulty: 11,
        id: "JOI14_scarecrows",
        year: 2014,
        comp: "JOIsp",
        day: "Day3-2",
        name: "Scarecrows",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2014/2014-sp-tasks/2014-sp-d3.pdf"
    },
    {
        difficulty: 10,
        id: "JOI14_voltage",
        year: 2014,
        comp: "JOIsp",
        day: "Day3-3",
        name: "Voltage",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2014/2014-sp-tasks/2014-sp-d3.pdf"
    },
    {
        difficulty: 11,
        id: "JOI14_constellation2",
        year: 2014,
        comp: "JOIsp",
        day: "Day4-1",
        name: "Constellation 2",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2014/2014-sp-tasks/2014-sp-d4.pdf"
    },
    {
        difficulty: 12,
        id: "JOI14_kanji",
        year: 2014,
        comp: "JOIsp",
        day: "Day4-2",
        name: "Kanji Shiritori",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2014/2014-sp-tasks/2014-sp-d4.pdf"
    },
    {
        difficulty: 7,
        id: "JOI14_straps",
        year: 2014,
        comp: "JOIsp",
        day: "Day4-3",
        name: "Straps",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2014/2014-sp-tasks/2014-sp-d4.pdf"
    },
    {
        difficulty: 8,
        id: "JOI15_copypaste2",
        year: 2015,
        comp: "JOIsp",
        day: "Day1-1",
        name: "Copy and Paste 2",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2015/2015-sp-tasks/2015-sp-d1.pdf"
    },
    {
        difficulty: 7,
        id: "JOI15_enjoi",
        year: 2015,
        comp: "JOIsp",
        day: "Day1-2",
        name: "En-JOI-able Logo Design",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2015/2015-sp-tasks/2015-sp-d1.pdf"
    },
    {
        difficulty: 10,
        id: "JOI15_growing2",
        year: 2015,
        comp: "JOIsp",
        day: "Day1-3",
        name: "Growing Vegetables is Fun 2",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2015/2015-sp-tasks/2015-sp-d1.pdf"
    },
    {
        difficulty: 9,
        id: "JOI15_ioioi_cards",
        year: 2015,
        comp: "JOIsp",
        day: "Day1-4",
        name: "IOIOI Cards",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2015/2015-sp-tasks/2015-sp-d1.pdf"
    },
    {
        difficulty: 8,
        id: "",
        year: 2015,
        comp: "JOIsp",
        day: "Day2-1",
        name: "Building 3",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2015/2015-sp-tasks/2015-sp-d2.pdf"
    },
    {
        difficulty: 10,
        id: "",
        year: 2015,
        comp: "JOIsp",
        day: "Day2-2",
        name: "Keys",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2015/2015-sp-tasks/2015-sp-d2.pdf"
    },
    {
        difficulty: 10,
        id: "",
        year: 2015,
        comp: "JOIsp",
        day: "Day2-3",
        name: "Road Development",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2015/2015-sp-tasks/2015-sp-d2.pdf"
    },
    {
        difficulty: 12,
        id: "",
        year: 2015,
        comp: "JOIsp",
        day: "Day3-1",
        name: "AAQQZ",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2015/2015-sp-tasks/2015-sp-d3.pdf"
    },
    {
        difficulty: 9,
        id: "",
        year: 2015,
        comp: "JOIsp",
        day: "Day3-2",
        name: "Card Game Is Great Fun",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2015/2015-sp-tasks/2015-sp-d3.pdf"
    },
    {
        difficulty: 10,
        id: "",
        year: 2015,
        comp: "JOIsp",
        day: "Day3-3",
        name: "Navigation",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2015/2015-sp-tasks/2015-sp-d3.pdf"
    },
    {
        difficulty: 8,
        id: "JOI15_inheritance",
        year: 2015,
        comp: "JOIsp",
        day: "Day4-1",
        name: "Inheritance",
        type: "Batch",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2015/2015-sp-tasks/2015-sp-d4.pdf"
    },
    {
        difficulty: 10,
        id: "JOI15_memory",
        year: 2015,
        comp: "JOIsp",
        day: "Day4-2",
        name: "Limited Memory",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2015/2015-sp-tasks/2015-sp-d4.pdf"
    },
    {
        difficulty: 12,
        id: "JOI15_walls",
        year: 2015,
        comp: "JOIsp",
        day: "Day4-3",
        name: "Walls",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2015/2015-sp-tasks/2015-sp-d4.pdf"
    },
    {
        difficulty: 10,
        id: "JOI16_matryoshka",
        year: 2016,
        comp: "JOIsp",
        day: "Day1-1",
        name: "Matryoshka",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2016/2016-sp-tasks/2016-sp-d1.pdf"
    },
    {
        difficulty: 9,
        id: "JOI16_memory2",
        year: 2016,
        comp: "JOIsp",
        day: "Day1-2",
        name: "Memory 2",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2016/2016-sp-tasks/2016-sp-d1.pdf"
    },
    {
        difficulty: 11,
        id: "JOI16_solitaire",
        year: 2016,
        comp: "JOIsp",
        day: "Day1-3",
        name: "Solitaire",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2016/2016-sp-tasks/2016-sp-d1.pdf"
    },
    {
        difficulty: 9,
        id: "JOI16_employment",
        year: 2016,
        comp: "JOIsp",
        day: "Day2-1",
        name: "Employment",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2016/2016-sp-tasks/2016-sp-d2.pdf"
    },
    {
        difficulty: 12,
        id: "JOI16_sandwich",
        year: 2016,
        comp: "JOIsp",
        day: "Day2-2",
        name: "Sandwich",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2016/2016-sp-tasks/2016-sp-d2.pdf"
    },
    {
        difficulty: 9,
        id: "JOI16_toilets",
        year: 2016,
        comp: "JOIsp",
        day: "Day2-3",
        name: "Toilets",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2016/2016-sp-tasks/2016-sp-d2.pdf"
    },
    {
        difficulty: 11,
        id: "JOI16_dungeon2",
        year: 2016,
        comp: "JOIsp",
        day: "Day3-1",
        name: "Dungeon 2",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2016/2016-sp-tasks/2016-sp-d3.pdf"
    },
    {
        difficulty: 11,
        id: "JOI16_sushi",
        year: 2016,
        comp: "JOIsp",
        day: "Day3-2",
        name: "Sushi",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2016/2016-sp-tasks/2016-sp-d3.pdf"
    },
    {
        difficulty: 9,
        id: "JOI16_telegraph",
        year: 2016,
        comp: "JOIsp",
        day: "Day3-3",
        name: "Telegraph",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2016/2016-sp-tasks/2016-sp-d3.pdf"
    },
    {
        difficulty: 10,
        id: "JOI16_skating",
        year: 2016,
        comp: "JOIsp",
        day: "Day4-1",
        name: "Dangerous Skating",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2016/2016-sp-tasks/2016-sp-d4.pdf"
    },
    {
        difficulty: 9,
        id: "JOI16_snowy",
        year: 2016,
        comp: "JOIsp",
        day: "Day4-2",
        name: "Snowy Roads",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2016/2016-sp-tasks/2016-sp-d4.pdf"
    },
    {
        difficulty: 10,
        id: "JOI16_worst_reporter2",
        year: 2016,
        comp: "JOIsp",
        day: "Day4-3",
        name: "Worst Reporter 2",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2016/2016-sp-tasks/2016-sp-d4.pdf"
    },
    {
        difficulty: 11,
        id: "JOI17_cultivation",
        year: 2017,
        comp: "JOIsp",
        day: "Day1-1",
        name: "Cultivation",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2017/2017-sp-tasks/2017-sp-d1.pdf"
    },
    {
        difficulty: 11,
        id: "JOI17_port_facility",
        year: 2017,
        comp: "JOIsp",
        day: "Day1-2",
        name: "Port Facility",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2017/2017-sp-tasks/2017-sp-d1.pdf"
    },
    {
        difficulty: 12,
        id: "JOI17_sparklers",
        year: 2017,
        comp: "JOIsp",
        day: "Day1-3",
        name: "Sparklers",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2017/2017-sp-tasks/2017-sp-d1.pdf"
    },
    {
        difficulty: 12,
        id: "JOI17_arranging_tickets",
        year: 2017,
        comp: "JOIsp",
        day: "Day2-1",
        name: "Arranging Tickets",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2017/2017-sp-tasks/2017-sp-d2.pdf"
    },
    {
        difficulty: 11,
        id: "JOI17_broken_device",
        year: 2017,
        comp: "JOIsp",
        day: "Day2-2",
        name: "Broken Device",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2017/2017-sp-tasks/2017-sp-d2.pdf"
    },
    {
        difficulty: 12,
        id: "JOI17_railway_trip",
        year: 2017,
        comp: "JOIsp",
        day: "Day2-3",
        name: "Railway Trip",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2017/2017-sp-tasks/2017-sp-d2.pdf"
    },
    {
        difficulty: 11,
        id: "JOI17_coach",
        year: 2017,
        comp: "JOIsp",
        day: "Day3-1",
        name: "Long Distance Coach",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2017/2017-sp-tasks/2017-sp-d3.pdf"
    },
    {
        difficulty: 11,
        id: "JOI17_long_mansion",
        year: 2017,
        comp: "JOIsp",
        day: "Day3-2",
        name: "Long Mansion",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2017/2017-sp-tasks/2017-sp-d3.pdf"
    },
    {
        difficulty: 12,
        id: "JOI17_park",
        year: 2017,
        comp: "JOIsp",
        day: "Day3-3",
        name: "Natural Park",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2017/2017-sp-tasks/2017-sp-d3.pdf"
    },
    {
        difficulty: 11,
        id: "JOI17_abduction2",
        year: 2017,
        comp: "JOIsp",
        day: "Day4-1",
        name: "Abduction 2",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2017/2017-sp-tasks/2017-sp-d4.pdf"
    },
    {
        difficulty: 12,
        id: "JOI17_city",
        year: 2017,
        comp: "JOIsp",
        day: "Day4-2",
        name: "City",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2017/2017-sp-tasks/2017-sp-d4.pdf"
    },
    {
        difficulty: 11,
        id: "JOI17_dragon2",
        year: 2017,
        comp: "JOIsp",
        day: "Day4-3",
        name: "Dragon 2",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2017/2017-sp-tasks/2017-sp-d4.pdf"
    },
    {
        difficulty: 11,
        id: "JOI18_construction",
        year: 2018,
        comp: "JOIsp",
        day: "Day1-1",
        name: "Construction of Highway",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2018/2018-sp-tasks/day1/construction.pdf"
    },
    {
        difficulty: 12,
        id: "JOI18_fences",
        year: 2018,
        comp: "JOIsp",
        day: "Day1-2",
        name: "Fences",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2018/2018-sp-tasks/day1/fences.pdf"
    },
    {
        difficulty: 9,
        id: "JOI18_tents",
        year: 2018,
        comp: "JOIsp",
        day: "Day1-3",
        name: "Tents",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2018/2018-sp-tasks/day1/tents.pdf"
    },
    {
        difficulty: 12,
        id: "JOI18_asceticism",
        year: 2018,
        comp: "JOIsp",
        day: "Day2-1",
        name: "Asceticism",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2018/2018-sp-tasks/day2/asceticism.pdf"
    },
    {
        difficulty: 12,
        id: "JOI18_road_service",
        year: 2018,
        comp: "JOIsp",
        day: "Day2-2",
        name: "Road Service",
        type: "Output Only",
        unavailable: true,
        statement_ja: "https://www.ioi-jp.org/camp/2018/2018-sp-tasks/day2/road.pdf"
    },
    {
        difficulty: 9,
        id: "JOI18_worst_reporter3",
        year: 2018,
        comp: "JOIsp",
        day: "Day2-3",
        name: "Worst Reporter 3",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2018/2018-sp-tasks/day2/worst_reporter3.pdf"
    },
    {
        difficulty: 10,
        id: "JOI18_airline",
        year: 2018,
        comp: "JOIsp",
        day: "Day3-1",
        name: "Airline Route Map",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2018/2018-sp-tasks/day3/airline.pdf"
    },
    {
        difficulty: 10,
        id: "JOI18_bitaro",
        year: 2018,
        comp: "JOIsp",
        day: "Day3-2",
        name: "Bitaro's Party",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2018/2018-sp-tasks/day3/bitaro.pdf"
    },
    {
        difficulty: 12,
        id: "JOI18_security_gate",
        year: 2018,
        comp: "JOIsp",
        day: "Day3-3",
        name: "Security Gate",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2018/2018-sp-tasks/day3/security_gate.pdf"
    },
    {
        difficulty: 12,
        id: "JOI18_candies",
        year: 2018,
        comp: "JOIsp",
        day: "Day4-1",
        name: "Candies",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2018/2018-sp-tasks/day4/candies.pdf"
    },
    {
        difficulty: 10,
        id: "JOI18_library",
        year: 2018,
        comp: "JOIsp",
        day: "Day4-2",
        name: "Library",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2018/2018-sp-tasks/day4/library.pdf"
    },
    {
        difficulty: 12,
        id: "JOI18_wild_boar",
        year: 2018,
        comp: "JOIsp",
        day: "Day4-3",
        name: "Wild Boar",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2018/2018-sp-tasks/day4/wild_boar.pdf"
    },
    {
        difficulty: 10,
        id: "JOI19_examination",
        year: 2019,
        comp: "JOIsp",
        day: "Day1-1",
        name: "Examination",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2019/2019-sp-tasks/day1/examination.pdf"
    },
    {
        difficulty: 11,
        id: "JOI19_meetings",
        year: 2019,
        comp: "JOIsp",
        day: "Day1-2",
        name: "Meetings",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2019/2019-sp-tasks/day1/meetings.pdf"
    },
    {
        difficulty: 11,
        id: "JOI19_naan",
        year: 2019,
        comp: "JOIsp",
        day: "Day1-3",
        name: "Naan",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2019/2019-sp-tasks/day1/naan.pdf"
    },
    {
        difficulty: 12,
        id: "JOI19_antennas",
        year: 2019,
        comp: "JOIsp",
        day: "Day2-1",
        name: "Two Antennas",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2019/2019-sp-tasks/day2/antennas.pdf"
    },
    {
        difficulty: 12,
        id: "JOI19_dishes",
        year: 2019,
        comp: "JOIsp",
        day: "Day2-2",
        name: "Two Dishes",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2019/2019-sp-tasks/day2/dishes.pdf"
    },
    {
        difficulty: 11,
        id: "JOI19_transportations",
        year: 2019,
        comp: "JOIsp",
        day: "Day2-3",
        name: "Two Transportations",
        type: "Communication",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2019/2019-sp-tasks/day2/transportations.pdf"
    },
    {
        difficulty: 12,
        id: "JOI19_designated_cities",
        year: 2019,
        comp: "JOIsp",
        day: "Day3-1",
        name: "Designated Cities",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2019/2019-sp-tasks/day3/designated.pdf"
    },
    {
        difficulty: 9,
        id: "JOI19_lamps",
        year: 2019,
        comp: "JOIsp",
        day: "Day3-2",
        name: "Lamps",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2019/2019-sp-tasks/day3/lamps.pdf"
    },
    {
        difficulty: 11,
        id: "JOI19_timeleap",
        year: 2019,
        comp: "JOIsp",
        day: "Day3-3",
        name: "Bitaro，who Leaps through Time",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2019/2019-sp-tasks/day3/timeleap.pdf"
    },
    {
        difficulty: 11,
        id: "JOI19_cake3",
        year: 2019,
        comp: "JOIsp",
        day: "Day4-1",
        name: "Cake 3",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2019/2019-sp-tasks/day4/cake3.pdf"
    },
    {
        difficulty: 10,
        id: "JOI19_mergers",
        year: 2019,
        comp: "JOIsp",
        day: "Day4-2",
        name: "Mergers",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2019/2019-sp-tasks/day4/mergers.pdf"
    },
    {
        difficulty: 12,
        id: "JOI19_minerals",
        year: 2019,
        comp: "JOIsp",
        day: "Day4-3",
        name: "Minerals",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2019/2019-sp-tasks/day4/minerals.pdf"
    },
    {
        difficulty: 9,
        id: "JOI20_building4",
        year: 2020,
        comp: "JOIsp",
        day: "Day1-1",
        name: "Building 4",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2020/2020-sp-tasks/day1/building4.pdf"
    },
    {
        difficulty: 12,
        id: "JOI20_hamburg",
        year: 2020,
        comp: "JOIsp",
        day: "Day1-2",
        name: "Hamburg Steak",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2020/2020-sp-tasks/day1/hamburg.pdf"
    },
    {
        difficulty: 12,
        id: "JOI20_sweeping",
        year: 2020,
        comp: "JOIsp",
        day: "Day1-3",
        name: "Sweeping",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2020/2020-sp-tasks/day1/sweeping.pdf"
    },
    {
        difficulty: 12,
        id: "JOI20_chameleon",
        year: 2020,
        comp: "JOIsp",
        day: "Day2-1",
        name: "Chameleon's Love",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2020/2020-sp-tasks/day2/chameleon.pdf"
    },
    {
        difficulty: 11,
        id: "JOI20_joitter2",
        year: 2020,
        comp: "JOIsp",
        day: "Day2-2",
        name: "Making Friends on Joitter is Fun",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2020/2020-sp-tasks/day2/joitter2.pdf"
    },
    {
        difficulty: 12,
        id: "JOI20_ruins3",
        year: 2020,
        comp: "JOIsp",
        day: "Day2-3",
        name: "Ruins 3",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2020/2020-sp-tasks/day2/ruins3.pdf"
    },
    {
        difficulty: 12,
        id: "JOI20_constellation3",
        year: 2020,
        comp: "JOIsp",
        day: "Day3-1",
        name: "Constellation 3",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2020/2020-sp-tasks/day3/constellation3.pdf"
    },
    {
        difficulty: 11,
        id: "JOI20_harvest",
        year: 2020,
        comp: "JOIsp",
        day: "Day3-2",
        name: "Harvest",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2020/2020-sp-tasks/day3/harvest3.pdf"
    },
    {
        difficulty: 11,
        id: "JOI20_stray",
        year: 2020,
        comp: "JOIsp",
        day: "Day3-3",
        name: "Stray Cat",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2020/2020-sp-tasks/day3/stray.pdf"
    },
    {
        difficulty: 11,
        id: "JOI20_capital_city",
        year: 2020,
        comp: "JOIsp",
        day: "Day4-1",
        name: "Capital City",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2020/2020-sp-tasks/day4/capital_city.pdf"
    },
    {
        difficulty: 11,
        id: "JOI20_dango2",
        year: 2020,
        comp: "JOIsp",
        day: "Day4-2",
        name: "Legendary Dango Maker",
        type: "Output Only",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2020/2020-sp-tasks/day4/dango2.pdf"
    },
    {
        difficulty: 11,
        id: "JOI20_treatment",
        year: 2020,
        comp: "JOIsp",
        day: "Day4-3",
        name: "Treatment Project",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2020/2020-sp-tasks/day4/treatment.pdf"
    },
    {
        difficulty: 13,
        id: "JOI21_aerobatics",
        year: 2021,
        comp: "JOIsp",
        day: "Day1-1",
        name: "Aerobatics",
        type: "Output Only",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2021/2021-sp-tasks/day1/aerobatics.pdf"
    },
    {
        difficulty: 11,
        id: "JOI21_fever",
        year: 2021,
        comp: "JOIsp",
        day: "Day1-2",
        name: "IOI Fever",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2021/2021-sp-tasks/day1/fever.pdf"
    },
    {
        difficulty: 11,
        id: "JOI21_foodcourt",
        year: 2021,
        comp: "JOIsp",
        day: "Day1-3",
        name: "Food Court",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2021/2021-sp-tasks/day1/foodcourt.pdf"
    },
    {
        difficulty: 11,
        id: "JOI21_escape_route",
        year: 2021,
        comp: "JOIsp",
        day: "Day2-1",
        name: "Escape Route",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2021/2021-sp-tasks/day2/escape_route.pdf"
    },
    {
        difficulty: 10,
        id: "JOI21_road_construction",
        year: 2021,
        comp: "JOIsp",
        day: "Day2-2",
        name: "Road Construction",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2021/2021-sp-tasks/day2/road_construction.pdf"
    },
    {
        difficulty: 13,
        id: "JOI21_shopping",
        year: 2021,
        comp: "JOIsp",
        day: "Day2-3",
        name: "Shopping",
        type: "Communication",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2021/2021-sp-tasks/day2/shopping.pdf"
    },
    {
        difficulty: 11,
        id: "JOI21_ancient_machine",
        year: 2021,
        comp: "JOIsp",
        day: "Day3-1",
        name: "Ancient Machine",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2021/2021-sp-tasks/day3/ancient_machine.pdf"
    },
    {
        difficulty: 11,
        id: "JOI21_bodyguard",
        year: 2021,
        comp: "JOIsp",
        day: "Day3-2",
        name: "Bodyguard",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2021/2021-sp-tasks/day3/bodyguard.pdf"
    },
    {
        difficulty: 11,
        id: "JOI21_meetings2",
        year: 2021,
        comp: "JOIsp",
        day: "Day3-3",
        name: "Meetings 2",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2021/2021-sp-tasks/day3/meetings2.pdf"
    },
    {
        difficulty: 10,
        id: "JOI21_event2",
        year: 2021,
        comp: "JOIsp",
        day: "Day4-1",
        name: "Event Hopping 2",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2021/2021-sp-tasks/day4/event2.pdf"
    },
    {
        difficulty: 12,
        id: "JOI21_navigation2",
        year: 2021,
        comp: "JOIsp",
        day: "Day4-2",
        name: "Navigation 2",
        type: "Communication",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2021/2021-sp-tasks/day4/navigation2.pdf"
    },
    {
        difficulty: 11,
        id: "JOI21_worst_reporter4",
        year: 2021,
        comp: "JOIsp",
        day: "Day4-3",
        name: "Worst Reporter 4",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2021/2021-sp-tasks/day4/worst_reporter4.pdf"
    },
    {
        difficulty: "",
        id: "JOI22_jail",
        year: 2022,
        comp: "JOIsp",
        day: "Day1-1",
        name: "Jail",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2022/2022-sp-tasks/contest1/jail.pdf"
    },
    {
        difficulty: "",
        id: "JOI22_kyoto",
        year: 2022,
        comp: "JOIsp",
        day: "Day1-2",
        name: "Sightseeing in Kyoto",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2022/2022-sp-tasks/contest1/kyoto.pdf"
    },
    {
        difficulty: "",
        id: "JOI22_misspelling",
        year: 2022,
        comp: "JOIsp",
        day: "Day1-3",
        name: "Misspelling",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2022/2022-sp-tasks/contest1/misspelling.pdf"
    },
    {
        difficulty: "",
        id: "JOI22_copypaste3",
        year: 2022,
        comp: "JOIsp",
        day: "Day2-1",
        name: "Copy and Paste 3",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2022/2022-sp-tasks/contest2/copypaste3.pdf"
    },
    {
        difficulty: "",
        id: "JOI22_flights",
        year: 2022,
        comp: "JOIsp",
        day: "Day2-2",
        name: "Flights",
        type: "Communication",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2022/2022-sp-tasks/contest2/flights.pdf"
    },
    {
        difficulty: "",
        id: "JOI22_team",
        year: 2022,
        comp: "JOIsp",
        day: "Day2-3",
        name: "Team Contest",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2022/2022-sp-tasks/contest2/team.pdf"
    },
    {
        difficulty: "",
        id: "JOI22_device2",
        year: 2022,
        comp: "JOIsp",
        day: "Day3-1",
        name: "Broken Device 2",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2022/2022-sp-tasks/contest3/device2.pdf"
    },
    {
        difficulty: "",
        id: "JOI22_sprinkler",
        year: 2022,
        comp: "JOIsp",
        day: "Day3-2",
        name: "Sprinkler",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2022/2022-sp-tasks/contest3/sprinkler.pdf"
    },
    {
        difficulty: "",
        id: "JOI22_sugar",
        year: 2022,
        comp: "JOIsp",
        day: "Day3-3",
        name: "Ants and Sugar",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2022/2022-sp-tasks/contest3/sugar.pdf"
    },
    {
        difficulty: "",
        id: "JOI22_dango3",
        year: 2022,
        comp: "JOIsp",
        day: "Day4-1",
        name: "Super Dango Maker",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2022/2022-sp-tasks/contest4/dango3.pdf"
    },
    {
        difficulty: "",
        id: "JOI22_fish2",
        year: 2022,
        comp: "JOIsp",
        day: "Day4-2",
        name: "Fish 2",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2022/2022-sp-tasks/contest4/fish2.pdf"
    },
    {
        difficulty: "",
        id: "JOI22_reconstruction",
        year: 2022,
        comp: "JOIsp",
        day: "Day4-3",
        name: "Reconstruction Project",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/camp/2022/2022-sp-tasks/contest4/reconstruction.pdf"
    },
    {
        difficulty: '',
        id: "JOI13_dispartiy",
        year: 2013,
        comp: "JOIop",
        day: "1",
        name: "Vote-Value Disparity",
        type: "Batch",
        unavailable: true,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2013/disparity-ja.pdf"
    },
    {
        difficulty: '',
        id: "JOI13_synchronization",
        year: 2013,
        comp: "JOIop",
        day: "2",
        name: "Synchronization",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2013/synchronization-ja.pdf"
    },
    {
        difficulty: '',
        id: "JOI13_watching",
        year: 2013,
        comp: "JOIop",
        day: "3",
        name: "Watching",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2013/watching-ja.pdf"
    },
    {
        difficulty: '',
        id: "JOI14_factories",
        year: 2014,
        comp: "JOIop",
        day: "Day1-1",
        name: "Factories",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2014/2014-open-d1-factories.pdf"
    },
    {
        difficulty: '',
        id: "JOI14_fortune_telling_2",
        year: 2014,
        comp: "JOIop",
        day: "Day1-2",
        name: "Fortune Telling 2",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2014/2014-open-d1-fortune_telling2.pdf"
    },
    {
        difficulty: '',
        id: "JOI14_space_pirate",
        year: 2014,
        comp: "JOIop",
        day: "Day1-3",
        name: "Space Pirate",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2014/2014-open-d1-space_pirate.pdf"
    },
    {
        difficulty: '',
        id: "JOI14_migration",
        year: 2014,
        comp: "JOIop",
        day: "Day2-1",
        name: "Project of Migration",
        type: "Output Only",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2014/2014-open-d2-migration.pdf"
    },
    {
        difficulty: '',
        id: "JOI14_pinball",
        year: 2014,
        comp: "JOIop",
        day: "Day2-2",
        name: "Pinball",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2014/2014-open-d2-pinball.pdf"
    },
    {
        difficulty: '',
        id: "JOI14_secret",
        year: 2014,
        comp: "JOIop",
        day: "Day2-3",
        name: "Secret",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2014/2014-open-d2-secret.pdf"
    },
    {
        difficulty: '',
        id: "JOI15_colored_tiles",
        year: 2015,
        comp: "JOIop",
        day: "1",
        name: "Colored Tiles",
        type: "Batch",
        unavailable: true,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2015/2015-open-colored_tiles.pdf"
    },
    {
        difficulty: '',
        id: "JOI15_election_campaign",
        year: 2015,
        comp: "JOIop",
        day: "2",
        name: "Election Campaign",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2015/2015-open-election_campaign.pdf"
    },
    {
        difficulty: '',
        id: "JOI15_sterilizing",
        year: 2015,
        comp: "JOIop",
        day: "3",
        name: "Sterilizing Spray",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2015/2015-open-sterilizing.pdf"
    },
    {
        difficulty: '',
        id: "JOI16_joiris",
        year: 2016,
        comp: "JOIop",
        day: "1",
        name: "JOIRIS",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2016/2016-open-joiris.pdf"
    },
    {
        difficulty: '',
        id: "JOI16_selling_rna",
        year: 2016,
        comp: "JOIop",
        day: "2",
        name: "Selling RNA Strands",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2016/2016-open-selling_rna.pdf"
    },
    {
        difficulty: '',
        id: "JOI16_skyscraper",
        year: 2016,
        comp: "JOIop",
        day: "3",
        name: "Skyscraper",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2016/2016-open-skyscraper.pdf"
    },
    {
        difficulty: '',
        id: "JOI17_amusument_park",
        year: 2017,
        comp: "JOIop",
        day: "1",
        name: "Amusement Park",
        type: "Interactive",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2017/2017-open-amusement_park-ja.pdf"
    },
    {
        difficulty: '',
        id: "JOI17_bulldozer",
        year: 2017,
        comp: "JOIop",
        day: "2",
        name: "Bulldozer",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2017/2017-open-bulldozer-ja.pdf"
    },
    {
        difficulty: '',
        id: "JOI17_golf",
        year: 2017,
        comp: "JOIop",
        day: "3",
        name: "Golf",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2017/2017-open-golf-ja.pdf"
    },
    {
        difficulty: '',
        id: "JOI18_bubblesort2",
        year: 2018,
        comp: "JOIop",
        day: "1",
        name: "Bubble Sort 2",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2018/2018-open-bubblesort2-ja.pdf"
    },
    {
        difficulty: '',
        id: "JOI18_catdog",
        year: 2018,
        comp: "JOIop",
        day: "2",
        name: "Cats and Dogs",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2018/2018-open-catdog-ja.pdf"
    },
    {
        difficulty: '',
        id: "JOI18_collapse",
        year: 2018,
        comp: "JOIop",
        day: "3",
        name: "Collapse",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2018/2018-open-collapse-sol-ja.pdf"
    },
    {
        difficulty: '',
        id: "JOI18_xylophone",
        year: 2018,
        comp: "JOIop",
        day: "4",
        name: "Xylophone",
        type: "Interactive",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2018/2018-open-xylophone-sol-ja.pdf"
    },
    {
        difficulty: '',
        id: "JOI19_jumps",
        year: 2019,
        comp: "JOIop",
        day: "1",
        name: "Triple Jump",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2019/jumps/2019-open-jumps-statement.pdf"
    },
    {
        difficulty: '',
        id: "JOI19_remittance",
        year: 2019,
        comp: "JOIop",
        day: "2",
        name: "Remittance",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2019/remittance/2019-open-remittance-statement.pdf"
    },
    {
        difficulty: '',
        id: "JOI19_virus",
        year: 2019,
        comp: "JOIop",
        day: "3",
        name: "Virus Experiment",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2019/virus/2019-open-virus-statement.pdf"
    },
    {
        difficulty: '',
        id: "JOI20_furniture",
        year: 2020,
        comp: "JOIop",
        day: "1",
        name: "Furniture",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2020/furniture/2020-open-furniture-statement.pdf"
    },
    {
        difficulty: '',
        id: "JOI20_monochrome",
        year: 2020,
        comp: "JOIop",
        day: "2",
        name: "Monochrome Points",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2020/monochrome/2020-open-monochrome-statement.pdf"
    },
    {
        difficulty: '',
        id: "JOI20_power",
        year: 2020,
        comp: "JOIop",
        day: "3",
        name: "Power Plant",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2020/power/2020-open-power-statement.pdf"
    },
    {
        difficulty: '',
        id: "JOI21_crossing",
        year: 2021,
        comp: "JOIop",
        day: "1",
        name: "Crossing",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2021/crossing/2021-open-crossing-statement.pdf"
    },
    {
        difficulty: '',
        id: "JOI21_financial",
        year: 2021,
        comp: "JOIop",
        day: "2",
        name: "Financial Report",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2021/financial/2021-open-financial-statement.pdf"
    },
    {
        difficulty: '',
        id: "JOI21_monster",
        year: 2021,
        comp: "JOIop",
        day: "3",
        name: "Monster Game",
        type: "Interactive",
        unavailable: false,
        statement_ja: "http://s3-ap-northeast-1.amazonaws.com/data.cms.ioi-jp.org/open-2021/monster/2021-open-monster-statement.pdf"
    },
    {
        difficulty: '',
        id: "APIO13_interference",
        year: 2013,
        comp: "APIO",
        day: "Practice",
        name: "Interference",
        type: "Output Only",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 10,
        id: "APIO13_robots",
        year: 2013,
        comp: "APIO",
        day: "1",
        name: "Robots",
        type: "Batch",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: '',
        id: "APIO13_toll",
        year: 2013,
        comp: "APIO",
        day: "2",
        name: "Toll",
        type: "Batch",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: '',
        id: "APIO13_tasksauthor",
        year: 2013,
        comp: "APIO",
        day: "3",
        name: "Tasks Author",
        type: "Batch",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 11,
        id: "APIO14_palindrome",
        year: 2014,
        comp: "APIO",
        day: "1",
        name: "Palindromes",
        type: "Batch",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 10,
        id: "APIO14_sequence",
        year: 2014,
        comp: "APIO",
        day: "2",
        name: "Split the sequence",
        type: "Batch",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 10,
        id: "APIO14_beads",
        year: 2014,
        comp: "APIO",
        day: "3",
        name: "Beads and wires",
        type: "Batch",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 9,
        id: "APIO15_sculpture",
        year: 2015,
        comp: "APIO",
        day: "1",
        name: "Bali Sculptures",
        type: "Batch",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 10,
        id: "APIO15_skyscraper",
        year: 2015,
        comp: "APIO",
        day: "2",
        name: "Jakarta Skyscrapers",
        type: "Batch",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 10,
        id: "APIO15_bridge",
        year: 2015,
        comp: "APIO",
        day: "3",
        name: "Palembang Bridges",
        type: "Batch",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 10,
        id: "APIO16_boat",
        year: 2016,
        comp: "APIO",
        day: "1",
        name: "Boat",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://apio-olympiad.org/2016/tasks/boat/descriptions/jp_JP.pdf"
    },
    {
        difficulty: 11,
        id: "APIO16_fireworks",
        year: 2016,
        comp: "APIO",
        day: "2",
        name: "Fireworks",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://apio-olympiad.org/2016/tasks/fireworks/descriptions/jp_JP.pdf"
    },
    {
        difficulty: 10,
        id: "APIO16_gap",
        year: 2016,
        comp: "APIO",
        day: "3",
        name: "Gap",
        type: "Interactive",
        unavailable: false,
        statement_ja: "http://apio-olympiad.org/2016/tasks/gap/descriptions/jp_JP.pdf"
    },
    {
        difficulty: 12,
        id: "APIO17_rainbow",
        year: 2017,
        comp: "APIO",
        day: "1",
        name: "Land of the Rainbow Gold",
        type: "Batch",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 9,
        id: "APIO17_merchant",
        year: 2017,
        comp: "APIO",
        day: "2",
        name: "Travelling Merchant",
        type: "Batch",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 11,
        id: "APIO17_koala",
        year: 2017,
        comp: "APIO",
        day: "3",
        name: "Koala Game",
        type: "Interactive",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 11,
        id: "APIO18_new_home",
        year: 2018,
        comp: "APIO",
        day: "1",
        name: "New Home",
        type: "Batch",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 12,
        id: "APIO18_circle_selection",
        year: 2018,
        comp: "APIO",
        day: "2",
        name: "Circle selection",
        type: "Batch",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 11,
        id: "APIO18_duathlon",
        year: 2018,
        comp: "APIO",
        day: "3",
        name: "Duathlon",
        type: "Batch",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 8,
        id: "APIO19_strange_device",
        year: 2019,
        comp: "APIO",
        day: "1",
        name: "Strange Device",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://apio2019.ru/upload/statements/Japanese.pdf"
    },
    {
        difficulty: 11,
        id: "APIO19_bridges",
        year: 2019,
        comp: "APIO",
        day: "2",
        name: "Bridges",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://apio2019.ru/upload/statements/Japanese.pdf"
    },
    {
        difficulty: 11,
        id: "APIO19_street_lamps",
        year: 2019,
        comp: "APIO",
        day: "3",
        name: "Street Lamps",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://apio2019.ru/upload/statements/Japanese.pdf"
    },
    {
        difficulty: 10,
        id: "APIO20_paint",
        year: 2020,
        comp: "APIO",
        day: "1",
        name: "Painting Walls",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://apio2020.toki.id/assets/statements/paint_ja.pdf"
    },
    {
        difficulty: 10,
        id: "APIO20_swap",
        year: 2020,
        comp: "APIO",
        day: "2",
        name: "Swapping Cities",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://apio2020.toki.id/assets/statements/swap_ja.pdf"
    },
    {
        difficulty: 11,
        id: "APIO20_fun",
        year: 2020,
        comp: "APIO",
        day: "3",
        name: "Fun Tour",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://apio2020.toki.id/assets/statements/fun_ja.pdf"
    },
    {
        difficulty: 12,
        id: "APIO21_hexagon",
        year: 2021,
        comp: "APIO",
        day: "1",
        name: "Hexagonal Territory",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://github.com/ia-toki/apio-2021-statements/blob/master/hexagon/ja_JP.pdf"
    },
    {
        difficulty: 10,
        id: "APIO21_jumps",
        year: 2021,
        comp: "APIO",
        day: "2",
        name: "Rainforest Jumps",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://github.com/ia-toki/apio-2021-statements/blob/master/jumps/ja_JP.pdf"
    },
    {
        difficulty: 11,
        id: "APIO21_roads",
        year: 2021,
        comp: "APIO",
        day: "3",
        name: "Road Closures",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://github.com/ia-toki/apio-2021-statements/blob/master/roads/ja_JP.pdf"
    },
    {
        difficulty: "",
        id: "APIO22_mars",
        year: 2022,
        comp: "APIO",
        day: "1",
        name: "Mars",
        type: "Communication",
        unavailable: false,
        statement_ja: "https://github.com/apio2022/apio2022_tasks/raw/master/Statements/mars/mars%20ja_JP.pdf"
    },
    {
        difficulty: "",
        id: "APIO22_game",
        year: 2022,
        comp: "APIO",
        day: "2",
        name: "Game",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://github.com/apio2022/apio2022_tasks/raw/master/Statements/game/game%20ja_JP.pdf"
    },
    {
        difficulty: "",
        id: "APIO22_perm",
        year: 2022,
        comp: "APIO",
        day: "3",
        name: "Permucation",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://github.com/apio2022/apio2022_tasks/raw/master/Statements/perm/perm%20ja_JP.pdf"
    },
    {
        difficulty: 9,
        id: "IOI07_aliens",
        year: 2007,
        comp: "IOI",
        day: "Day1-1",
        name: "Aliens",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2007/problem/day1/aliens-prob-j.pdf"
    },
    {
        difficulty: 9,
        id: "IOI07_flood",
        year: 2007,
        comp: "IOI",
        day: "Day1-2",
        name: "Flood",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2007/problem/day1/flood-prob-j.pdf"
    },
    {
        difficulty: 11,
        id: "IOI07_sails",
        year: 2007,
        comp: "IOI",
        day: "Day1-3",
        name: "Sails",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2007/problem/day1/sails-prob-j.pdf"
    },
    {
        difficulty: 7,
        id: "IOI07_miners",
        year: 2007,
        comp: "IOI",
        day: "Day2-1",
        name: "Miners",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2007/problem/day2/miners-prob-j.pdf"
    },
    {
        difficulty: 11,
        id: "IOI07_pairs",
        year: 2007,
        comp: "IOI",
        day: "Day2-2",
        name: "Pairs",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2007/problem/day2/pairs-prob-j.pdf"
    },
    {
        difficulty: '',
        id: "IOI07_training",
        year: 2007,
        comp: "IOI",
        day: "Day2-3",
        name: "Training",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2007/problem/day2/training-prob-j.pdf"
    },
    {
        difficulty: 7,
        id: "IOI08_printer",
        year: 2008,
        comp: "IOI",
        day: "Day1-1",
        name: "Type Printer",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2008/problems/Day1_jpn/type_printer_j.pdf"
    },
    {
        difficulty: 11,
        id: "IOI08_islands",
        year: 2008,
        comp: "IOI",
        day: "Day1-2",
        name: "Islands",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2008/problems/Day1_jpn/islands_j.pdf"
    },
    {
        difficulty: '',
        id: "IOI08_fish",
        year: 2008,
        comp: "IOI",
        day: "Day1-3",
        name: "Fish",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2008/problems/Day1_jpn/fish_j.pdf"
    },
    {
        difficulty: 8,
        id: "IOI08_linear_garden",
        year: 2008,
        comp: "IOI",
        day: "Day2-1",
        name: "Linear Garden",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2008/problems/Day2_jpn/lg_j.pdf"
    },
    {
        difficulty: 8,
        id: "IOI08_teleporters",
        year: 2008,
        comp: "IOI",
        day: "Day2-2",
        name: "Teleporters",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2008/problems/Day2_jpn/teleporters_j.pdf"
    },
    {
        difficulty: '',
        id: "IOI08_pyramid_base",
        year: 2008,
        comp: "IOI",
        day: "Day2-3",
        name: "Pyramid Base",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2008/problems/Day2_jpn/Pyramid_Base_j.pdf"
    },
    {
        difficulty: '',
        id: "IOI09_archery",
        year: 2009,
        comp: "IOI",
        day: "Day1-1",
        name: "Archery",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2009/problems/day1/Archery_jp.pdf"
    },
    {
        difficulty: 8,
        id: "IOI09_hiring",
        year: 2009,
        comp: "IOI",
        day: "Day1-2",
        name: "Hiring",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2009/problems/day1/Hiring_jp.pdf"
    },
    {
        difficulty: 5,
        id: "IOI09_poi",
        year: 2009,
        comp: "IOI",
        day: "Day1-3",
        name: "Poi",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2009/problems/day1/POI_jp.pdf"
    },
    {
        difficulty: 7,
        id: "IOI09_raisins",
        year: 2009,
        comp: "IOI",
        day: "Day1-4",
        name: "Raisins",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2009/problems/day1/Raisins_jp.pdf"
    },
    {
        difficulty: 5,
        id: "IOI09_garage",
        year: 2009,
        comp: "IOI",
        day: "Day2-1",
        name: "Garage",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2009/problems/day2/Garage_jp.pdf"
    },
    {
        difficulty: 7,
        id: "IOI09_mecho",
        year: 2009,
        comp: "IOI",
        day: "Day2-2",
        name: "Mecho",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2009/problems/day2/Mecho_jp.pdf"
    },
    {
        difficulty: '',
        id: "IOI09_regions",
        year: 2009,
        comp: "IOI",
        day: "Day2-3",
        name: "Regions",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2009/problems/day2/Regions_jp.pdf"
    },
    {
        difficulty: 9,
        id: "IOI09_salesman",
        year: 2009,
        comp: "IOI",
        day: "Day2-4",
        name: "Salesman",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2009/problems/day2/Salesman_jp.pdf"
    },
    {
        difficulty: 4,
        id: "IOI10_cluedo",
        year: 2010,
        comp: "IOI",
        day: "Day1-1",
        name: "Cluedo",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2010/tasks/tasks_jpn/day1/t1_cluedo/index.html"
    },
    {
        difficulty: 13,
        id: "IOI10_hottercolder",
        year: 2010,
        comp: "IOI",
        day: "Day1-2",
        name: "Hotter Colder",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2010/tasks/tasks_jpn/day1/t2_hottercolder/index.html"
    },
    {
        difficulty: 9,
        id: "IOI10_quality",
        year: 2010,
        comp: "IOI",
        day: "Day1-3",
        name: "Quality Of Living",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2010/tasks/tasks_jpn/day1/t3_quality/index.html"
    },
    {
        difficulty: 12,
        id: "IOI10_languages",
        year: 2010,
        comp: "IOI",
        day: "Day1-4",
        name: "Languages",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2010/tasks/tasks_jpn/day1/t4_language/index.html"
    },
    {
        difficulty: 4,
        id: "IOI10_memory",
        year: 2010,
        comp: "IOI",
        day: "Day2-1",
        name: "Memory",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2010/tasks/tasks_jpn/day2/t1_memory/index.html"
    },
    {
        difficulty: 8,
        id: "IOI10_traffic",
        year: 2010,
        comp: "IOI",
        day: "Day2-2",
        name: "Traffic",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2010/tasks/tasks_jpn/day2/t2_traffic/index.html"
    },
    {
        difficulty: '',
        id: "IOI10_maze",
        year: 2010,
        comp: "IOI",
        day: "Day2-3",
        name: "Maze",
        type: "Output Only",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2010/tasks/tasks_jpn/day2/t3_maze/index.html"
    },
    {
        difficulty: 12,
        id: "IOI10_saveit",
        year: 2010,
        comp: "IOI",
        day: "Day2-4",
        name: "Saveit",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2010/tasks/tasks_jpn/day2/t4_saveit/index.html"
    },
    {
        difficulty: 9,
        id: "IOI11_garden",
        year: 2011,
        comp: "IOI",
        day: "Day1-1",
        name: "Tropical Garden",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2011/tasks/day1/garden_jpn.pdf"
    },
    {
        difficulty: 10,
        id: "IOI11_race",
        year: 2011,
        comp: "IOI",
        day: "Day1-2",
        name: "Race",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2011/tasks/day1/race_jpn.pdf"
    },
    {
        difficulty: 8,
        id: "IOI11_ricehub",
        year: 2011,
        comp: "IOI",
        day: "Day1-3",
        name: "Rice Hub",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2011/tasks/day1/ricehub_jpn.pdf"
    },
    {
        difficulty: 9,
        id: "IOI11_crocodile",
        year: 2011,
        comp: "IOI",
        day: "Day2-1",
        name: "Crocodile's Underground City",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2011/tasks/day2/crocodile_jpn.pdf"
    },
    {
        difficulty: 11,
        id: "IOI11_elephants",
        year: 2011,
        comp: "IOI",
        day: "Day2-2",
        name: "Dancing Elephants",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2011/tasks/day2/elephants_jpn.pdf"
    },
    {
        difficulty: 10,
        id: "IOI11_parrots",
        year: 2011,
        comp: "IOI",
        day: "Day2-3",
        name: "Parrots",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2011/tasks/day2/parrots_jpn.pdf"
    },
    {
        difficulty: 11,
        id: "IOI12_odometer",
        year: 2012,
        comp: "IOI",
        day: "Day1-1",
        name: "Odometer",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2012/tasks/odometer-jp.pdf"
    },
    {
        difficulty: 11,
        id: "IOI12_rings",
        year: 2012,
        comp: "IOI",
        day: "Day1-2",
        name: "Parachute rings",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2012/tasks/rings-jp.pdf"
    },
    {
        difficulty: 9,
        id: "IOI12_scrivener",
        year: 2012,
        comp: "IOI",
        day: "Day1-3",
        name: "Crayfish scrivener",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2012/tasks/scrivener-jp.pdf"
    },
    {
        difficulty: 11,
        id: "IOI12_city",
        year: 2012,
        comp: "IOI",
        day: "Day2-1",
        name: "Ideal city",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2012/tasks/city-jp.pdf"
    },
    {
        difficulty: 11,
        id: "IOI12_supper",
        year: 2012,
        comp: "IOI",
        day: "Day2-2",
        name: "Last supper",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2012/tasks/supper-jp.pdf"
    },
    {
        difficulty: 9,
        id: "IOI12_tournament",
        year: 2012,
        comp: "IOI",
        day: "Day2-3",
        name: "Jousting tournament",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2012/tasks/tournament-jp.pdf"
    },
    {
        difficulty: 10,
        id: "IOI13_dreaming",
        year: 2013,
        comp: "IOI",
        day: "Day1-1",
        name: "Dreaming",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://www.ioi2013.org/wp-content/uploads/tasks/day1/dreaming/Dreaming%20ja%20(JPN).pdf"
    },
    {
        difficulty: 10,
        id: "IOI13_artclass",
        year: 2013,
        comp: "IOI",
        day: "Day1-2",
        name: "Art Class",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://www.ioi2013.org/wp-content/uploads/tasks/day1/artclass/Art%20class%20ja%20(JPN).pdf"
    },
    {
        difficulty: 12,
        id: "IOI13_wombats",
        year: 2013,
        comp: "IOI",
        day: "Day1-3",
        name: "Wombats",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://www.ioi2013.org/wp-content/uploads/tasks/day1/wombats/Wombats%20ja%20(JPN).pdf"
    },
    {
        difficulty: 8,
        id: "IOI13_cave",
        year: 2013,
        comp: "IOI",
        day: "Day2-1",
        name: "Cave",
        type: "Interactive",
        unavailable: false,
        statement_ja: "http://www.ioi2013.org/wp-content/uploads/tasks/day2/cave/cave%20-%20JPN%20(ja).pdf"
    },
    {
        difficulty: 9,
        id: "IOI13_robots",
        year: 2013,
        comp: "IOI",
        day: "Day2-2",
        name: "Robots",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://www.ioi2013.org/wp-content/uploads/tasks/day2/robots/robots%20-%20JPN%20(ja).pdf"
    },
    {
        difficulty: 10,
        id: "IOI13_game",
        year: 2013,
        comp: "IOI",
        day: "Day2-3",
        name: "Game",
        type: "Interactive",
        unavailable: false,
        statement_ja: "http://www.ioi2013.org/wp-content/uploads/tasks/day2/game/game%20-%20JPN%20(ja).pdf"
    },
    {
        difficulty: 11,
        id: "IOI14_rail",
        year: 2014,
        comp: "IOI",
        day: "Day1-1",
        name: "Rail",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2014/tasks/rail-jp.pdf"
    },
    {
        difficulty: 10,
        id: "IOI14_wall",
        year: 2014,
        comp: "IOI",
        day: "Day1-2",
        name: "Wall",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2014/tasks/wall-jp.pdf"
    },
    {
        difficulty: 10,
        id: "IOI14_game",
        year: 2014,
        comp: "IOI",
        day: "Day1-3",
        name: "Game",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2014/tasks/game-jp.pdf"
    },
    {
        difficulty: 8,
        id: "IOI14_gondola",
        year: 2014,
        comp: "IOI",
        day: "Day2-1",
        name: "Gondola",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2014/tasks/gondola-jp.pdf"
    },
    {
        difficulty: 11,
        id: "IOI14_friend",
        year: 2014,
        comp: "IOI",
        day: "Day2-2",
        name: "Friend",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2014/tasks/friend-jp.pdf"
    },
    {
        difficulty: 11,
        id: "IOI14_holiday",
        year: 2014,
        comp: "IOI",
        day: "Day2-3",
        name: "Holiday",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2014/tasks/holiday-jp.pdf"
    },
    {
        difficulty: 9,
        id: "IOI15_boxes",
        year: 2015,
        comp: "IOI",
        day: "Day1-1",
        name: "Boxes with souvenirs",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2015/tasks/boxes-jp.pdf"
    },
    {
        difficulty: 12,
        id: "IOI15_scales",
        year: 2015,
        comp: "IOI",
        day: "Day1-2",
        name: "Scales",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2015/tasks/scales-jp.pdf"
    },
    {
        difficulty: 11,
        id: "IOI15_teams",
        year: 2015,
        comp: "IOI",
        day: "Day1-3",
        name: "Teams",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2015/tasks/teams-jp.pdf"
    },
    {
        difficulty: 10,
        id: "IOI15_horses",
        year: 2015,
        comp: "IOI",
        day: "Day2-1",
        name: "Horses",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2015/tasks/horses-jp.pdf"
    },
    {
        difficulty: 10,
        id: "IOI15_sorting",
        year: 2015,
        comp: "IOI",
        day: "Day2-2",
        name: "Sorting",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2015/tasks/sorting-jp.pdf"
    },
    {
        difficulty: '',
        id: "IOI15_towns",
        year: 2015,
        comp: "IOI",
        day: "Day2-3",
        name: "Towns",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2015/tasks/towns-jp.pdf"
    },
    {
        difficulty: 6,
        id: "IOI16_tetris",
        year: 2016,
        comp: "IOI",
        day: "Day0-1",
        name: "Mini tetris",
        type: "Batch",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 2,
        id: "IOI16_reverse",
        year: 2016,
        comp: "IOI",
        day: "Day0-2",
        name: "Reversing a Sequence",
        type: "Batch",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 3,
        id: "IOI16_laugh",
        year: 2016,
        comp: "IOI",
        day: "Day0-3",
        name: "Laugh Analysis",
        type: "Batch",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 10,
        id: "IOI16_dna",
        year: 2016,
        comp: "IOI",
        day: "Day0-4",
        name: "Martian DNA",
        type: "Interactive",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 8,
        id: "IOI16_molecules",
        year: 2016,
        comp: "IOI",
        day: "Day1-1",
        name: "Detecting Molecules",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2016/tasks/day1-molecules-JPN.pdf"
    },
    {
        difficulty: 11,
        id: "IOI16_railroad",
        year: 2016,
        comp: "IOI",
        day: "Day1-2",
        name: "Roller Coaster Railroad",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2016/tasks/day1-railroad-JPN.pdf"
    },
    {
        difficulty: 12,
        id: "IOI16_shortcut",
        year: 2016,
        comp: "IOI",
        day: "Day1-3",
        name: "Shortcut",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2016/tasks/day1-shortcut-JPN.pdf"
    },
    {
        difficulty: 9,
        id: "IOI16_paint",
        year: 2016,
        comp: "IOI",
        day: "Day2-1",
        name: "Paint By Numbers",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2016/tasks/day2-paint-JPN.pdf"
    },
    {
        difficulty: 10,
        id: "IOI16_messy",
        year: 2016,
        comp: "IOI",
        day: "Day2-2",
        name: "Unscrambling a Messy Bug",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2016/tasks/day2-messy-JPN.pdf"
    },
    {
        difficulty: 12,
        id: "IOI16_aliens",
        year: 2016,
        comp: "IOI",
        day: "Day2-3",
        name: "Aliens",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2016/tasks/day2-aliens-JPN.pdf"
    },
    {
        difficulty: 10,
        id: "IOI17_mountains",
        year: 2017,
        comp: "IOI",
        day: "Day0-1",
        name: "Mountains",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2017/tasks/day0-mountains-JPN.pdf"
    },
    {
        difficulty: 9,
        id: "IOI17_cup",
        year: 2017,
        comp: "IOI",
        day: "Day0-2",
        name: "Cup of Jamshid",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2017/tasks/day0-cup-JPN.pdf"
    },
    {
        difficulty: 9,
        id: "IOI17_coins",
        year: 2017,
        comp: "IOI",
        day: "Day0-3",
        name: "Coins",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2017/tasks/day0-coins-JPN.pdf"
    },
    {
        difficulty: '',
        id: "IOI17_sudoku",
        year: 2017,
        comp: "IOI",
        day: "Day0-4",
        name: "Sudoku",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2017/tasks/day0-sudoku-JPN.pdf"
    },
    {
        difficulty: '',
        id: "IOI17_nowruz",
        year: 2017,
        comp: "IOI",
        day: "Day1-1",
        name: "Nowruz",
        type: "Output Only",
        unavailable: false,
        statement_ja: "http://ioi2017.org/tasks/day1/nowruz/nowruz-JPN.pdf"
    },
    {
        difficulty: 11,
        id: "IOI17_wiring",
        year: 2017,
        comp: "IOI",
        day: "Day1-2",
        name: "Wiring",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://ioi2017.org/tasks/day1/wiring/wiring-JPN.pdf"
    },
    {
        difficulty: 12,
        id: "IOI17_train",
        year: 2017,
        comp: "IOI",
        day: "Day1-3",
        name: "Toy Train",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://ioi2017.org/tasks/day1/train/train-JPN.pdf"
    },
    {
        difficulty: 10,
        id: "IOI17_prize",
        year: 2017,
        comp: "IOI",
        day: "Day2-1",
        name: "The Big Prize",
        type: "Interactive",
        unavailable: false,
        statement_ja: "http://ioi2017.org/tasks/day2/prize/prize-JPN.pdf"
    },
    {
        difficulty: 12,
        id: "IOI17_simurgh",
        year: 2017,
        comp: "IOI",
        day: "Day2-2",
        name: "Simurgh",
        type: "Interactive",
        unavailable: false,
        statement_ja: "http://ioi2017.org/tasks/day2/simurgh/simurgh-JPN.pdf"
    },
    {
        difficulty: 12,
        id: "IOI17_books",
        year: 2017,
        comp: "IOI",
        day: "Day2-3",
        name: "Ancient Books",
        type: "Batch",
        unavailable: false,
        statement_ja: "http://ioi2017.org/tasks/day2/books/books-JPN.pdf"
    },
    {
        difficulty: 8,
        id: "IOI18_combo",
        year: 2018,
        comp: "IOI",
        day: "Day1-1",
        name: "Combo",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://ioi2018.jp/wp-content/tasks/contest1/JPN-combo.pdf"
    },
    {
        difficulty: 12,
        id: "IOI18_seats",
        year: 2018,
        comp: "IOI",
        day: "Day1-2",
        name: "Seats",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://ioi2018.jp/wp-content/tasks/contest1/JPN-seats.pdf"
    },
    {
        difficulty: 11,
        id: "IOI18_werewolf",
        year: 2018,
        comp: "IOI",
        day: "Day1-3",
        name: "Werewolf",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://ioi2018.jp/wp-content/tasks/contest1/JPN-werewolf.pdf"
    },
    {
        difficulty: 11,
        id: "IOI18_doll",
        year: 2018,
        comp: "IOI",
        day: "Day2-1",
        name: "Mechanical Doll",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://ioi2018.jp/wp-content/tasks/contest2/JPN-doll.pdf"
    },
    {
        difficulty: 12,
        id: "IOI18_highway",
        year: 2018,
        comp: "IOI",
        day: "Day2-2",
        name: "Highway Tolls",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://ioi2018.jp/wp-content/tasks/contest2/JPN-highway.pdf"
    },
    {
        difficulty: 13,
        id: "IOI18_meetings",
        year: 2018,
        comp: "IOI",
        day: "Day2-3",
        name: "Meetings",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://ioi2018.jp/wp-content/tasks/contest2/JPN-meetings.pdf"
    },
    {
        difficulty: 11,
        id: "IOI19_job",
        year: 2019,
        comp: "IOI",
        day: "Day0-1",
        name: "Job Scheduling",
        type: "Batch",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 7,
        id: "IOI19_cycle",
        year: 2019,
        comp: "IOI",
        day: "Day0-2",
        name: "Lost in the cycle",
        type: "Interactive",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 10,
        id: "IOI19_transfer",
        year: 2019,
        comp: "IOI",
        day: "Day0-3",
        name: "Data Transfer",
        type: "Interactive",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: '',
        id: "IOI19_packing",
        year: 2019,
        comp: "IOI",
        day: "Day0-4",
        name: "Packing",
        type: "Output Only",
        unavailable: false,
        statement_ja: ""
    },
    {
        difficulty: 10,
        id: "IOI19_shoes",
        year: 2019,
        comp: "IOI",
        day: "Day1-1",
        name: "Arranging Shoes",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2019/tasks/day1-shoes-JPN.pdf"
    },
    {
        difficulty: 12,
        id: "IOI19_split",
        year: 2019,
        comp: "IOI",
        day: "Day1-2",
        name: "Split the Attractions",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2019/tasks/day1-split-JPN.pdf"
    },
    {
        difficulty: 11,
        id: "IOI19_rect",
        year: 2019,
        comp: "IOI",
        day: "Day1-3",
        name: "Rectangles",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2019/tasks/day1-rect-JPN.pdf"
    },
    {
        difficulty: '',
        id: "IOI19_line",
        year: 2019,
        comp: "IOI",
        day: "Day2-1",
        name: "Broken Line",
        type: "Output Only",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2019/tasks/day2-line-JPN.pdf"
    },
    {
        difficulty: 10,
        id: "IOI19_vision",
        year: 2019,
        comp: "IOI",
        day: "Day2-2",
        name: "Vision Program",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2019/tasks/day2-vision-JPN.pdf"
    },
    {
        difficulty: 12,
        id: "IOI19_walk",
        year: 2019,
        comp: "IOI",
        day: "Day2-3",
        name: "Sky Walking",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2019/tasks/day2-walk-JPN.pdf"
    },
    {
        difficulty: 7,
        id: "IOI20_gift",
        year: 2020,
        comp: "IOI",
        day: "Day0-1",
        name: "Handcrafted Gift",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2020/tasks/day0-gift-JPN.pdf"
    },
    {
        difficulty: '',
        id: "IOI20_squares",
        year: 2020,
        comp: "IOI",
        day: "Day0-2",
        name: "Painting Squares",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2020/tasks/day0-squares-JPN.pdf"
    },
    {
        difficulty: 9,
        id: "IOI20_routers",
        year: 2020,
        comp: "IOI",
        day: "Day0-3",
        name: "Finding Routers",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2020/tasks/day0-routers-JPN.pdf"
    },
    {
        difficulty: 8,
        id: "IOI20_jelly",
        year: 2020,
        comp: "IOI",
        day: "Day0-4",
        name: "Jelly Flavours",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2020/tasks/day0-jelly-JPN.pdf"
    },
    {
        difficulty: 12,
        id: "IOI20_plants",
        year: 2020,
        comp: "IOI",
        day: "Day1-1",
        name: "Comparing Plants",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2020/tasks/day1-plants-JPN.pdf"
    },
    {
        difficulty: 8,
        id: "IOI20_supertrees",
        year: 2020,
        comp: "IOI",
        day: "Day1-2",
        name: "Connecting Supertrees",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2020/tasks/day1-supertrees-JPN.pdf"
    },
    {
        difficulty: 12,
        id: "IOI20_tickets",
        year: 2020,
        comp: "IOI",
        day: "Day1-3",
        name: "Carnival Tickets",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2020/tasks/day1-tickets-JPN.pdf"
    },
    {
        difficulty: 11,
        id: "IOI20_biscuits",
        year: 2020,
        comp: "IOI",
        day: "Day2-1",
        name: "Packing Biscuits",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2020/tasks/day2-biscuits-JPN.pdf"
    },
    {
        difficulty: 12,
        id: "IOI20_mushrooms",
        year: 2020,
        comp: "IOI",
        day: "Day2-2",
        name: "Counting Mushrooms",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2020/tasks/day2-mushrooms-JPN.pdf"
    },
    {
        difficulty: 11,
        id: "IOI20_stations",
        year: 2020,
        comp: "IOI",
        day: "Day2-3",
        name: "Stations",
        type: "Interactive",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2020/tasks/day2-stations-JPN.pdf"
    },
    {
        difficulty: '',
        id: "IOI21_candies",
        year: 2021,
        comp: "IOI",
        day: "Day1-1",
        name: "Distributing Candies",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2021/tasks/day1-candies-JPN.pdf"
    },
    {
        difficulty: '',
        id: "IOI21_keys",
        year: 2021,
        comp: "IOI",
        day: "Day1-2",
        name: "Keys",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2021/tasks/day1-keys-JPN.pdf"
    },
    {
        difficulty: '',
        id: "IOI21_parks",
        year: 2021,
        comp: "IOI",
        day: "Day1-3",
        name: "Fountain Parks",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2021/tasks/day1-parks-JPN.pdf"
    },
    {
        difficulty: '',
        id: "IOI21_dna",
        year: 2021,
        comp: "IOI",
        day: "Day2-1",
        name: "Mutating DNA",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2021/tasks/day2-dna-JPN.pdf"
    },
    {
        difficulty: '',
        id: "IOI21_dungeons",
        year: 2021,
        comp: "IOI",
        day: "Day2-2",
        name: "Dungeons Game",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2021/tasks/day2-dungeons-JPN.pdf"
    },
    {
        difficulty: '',
        id: "IOI21_registers",
        year: 2021,
        comp: "IOI",
        day: "Day2-3",
        name: "Bit Shift Registers",
        type: "Batch",
        unavailable: false,
        statement_ja: "https://www.ioi-jp.org/ioi/2021/tasks/day2-registers-JPN.pdf"
    }
];